export const MontrealHourly = [
  {hour: '0 Am', temperature: 19, type: 'windy'},
  {hour: '1 Am', temperature: 18, type: 'windy'},
  {hour: '2 Am', temperature: 17, type: 'windy'},
  {hour: '3 Am', temperature: 16, type: 'windy'},
  {hour: '4 Am', temperature: 15, type: 'rainy'},
  {hour: '5 Am', temperature: 15, type: 'rainy'},
  {hour: '6 Am', temperature: 16, type: 'rainy'},
  {hour: '7 Am', temperature: 16, type: 'rainy'},
  {hour: '8 Am', temperature: 17, type: 'sunnyRainy'},
  {hour: '9 Am', temperature: 17, type: 'sunnyRainy'},
  {hour: '10 Am', temperature: 18, type: 'windy'},
  {hour: '11 Am', temperature: 18, type: 'windy'},
  {hour: '12 Am', temperature: 19, type: 'windy'},
];
