export const weatherData = [
  {
    temperature: 20,
    high: 25,
    low: 16,
    city: 'Baku',
    country: 'Azerbaijan',
    condition: 'Partly Cloudy',
    type: 'cloudy',
  },
  {
    temperature: 21,
    high: 24,
    low: 14,
    city: 'Texas',
    country: 'United States',
    condition: 'Tornado',
    type: 'tornado',
  },
  {
    temperature: 20,
    high: 21,
    low: 10,
    city: 'Toronto',
    country: 'Canada',
    condition: 'Fast Wind',
    type: 'windy',
  },
  {
    temperature: 19,
    high: 24,
    low: 18,
    city: 'Montreal',
    country: 'Canada',
    condition: 'Mid Rain',
    type: 'rainy',
  },
  {
    temperature: 13,
    high: 16,
    low: 8,
    city: 'Tokyo',
    country: 'Japan',
    condition: 'Showers',
    type: 'showering',
  },
  {
    temperature: 23,
    high: 26,
    low: 16,
    city: 'Tennessee',
    country: 'United States',
    condition: 'Tornado',
    type: 'tornado',
  },
  {
    temperature: 20,
    high: 25,
    low: 16,
    city: 'Baku',
    country: 'Azerbaijan',
    condition: 'Partly Cloudy',
    type: 'cloudy',
  },
  {
    temperature: 22,
    high: 24,
    low: 18,
    city: 'Istanbul',
    country: 'Turkey',
    condition: 'Mid Rain',
    type: 'rainy',
  },
  {
    temperature: 12,
    high: 16,
    low: 8,
    city: 'Moscow',
    country: 'Russia',
    condition: 'Fast Wind',
    type: 'windy',
  },
  {
    temperature: 18,
    high: 23,
    low: 19,
    city: 'Tbilisi',
    country: 'Georgia',
    condition: 'Partly Cloudy',
    type: 'cloudy',
  },
];
